name: Build

on:
  workflow_call:

jobs:
  build_typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build Common Typescript
        run: npm run build:common

      - name: Build Core Typescript
        run: npm run build:core
