name: CI - Push
on:
  push:
    branches:
      - main

jobs:
  format:
    name: Format
    uses: ./.github/workflows/format.yml
    secrets: inherit

  build:
    name: Build
    needs: format
    uses: ./.github/workflows/build.yml
    secrets: inherit
