name: Containerize

on:
  workflow_call:

jobs:
  core:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        working-directory: packages/core
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        working-directory: packages/core
        run: docker build . -t ghcr.io/${{github.repository}}:latest

      - name: Push Docker image to GitHub Container Registry
        working-directory: packages/core
        run: docker push ghcr.io/${{github.repository}}:latest
